default: 
  patreon:
    clientId: ''
    clientSecret: 'b11c7d64729a2dd8015fef67a720f05a03010ca21190cbe0a1194c4d642d3887'
  logLevel: 'TRACE'
  elastic: 
    minLogLevel: 'info'
  mongo: 'mongodb://localhost:27017'
  disableUnlinked: false
development: 
  mongo: 'mongodb://rnettest:rNet01test@db01.localhost.com:27017/rnettest'
